# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15e1a2ba1f7d8b4d55cdac08dbe187e325056e23e18fd116030c2cb12bfe0e97c44b9eda1c5010147ba9c5b229c8ff853d1fa4a5433c49739fe593b4317f1708

test:
  secret_key_base: 5bb89fded4ea35f1cef0ae96ff5303c66cfaec2a1c9238648dd668904f164aeab4954be4ad373b7d93c7f35f15aff5ab9ac270f4af672226cd7cfb85a3278e9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
